---

- name: 1. Instalando o helm repo
  shell: helm repo add stable {{ url_repo_helm }}
  register: prometheus_add_repo

- name: 2. Helm update
  shell: helm repo update
  register: prometheus_repo_update

- name: 3. Instalando o prometheus Operator
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_install

